version: "3"

services:
    webapp:
        build:
            context: ./bin/app
        container_name: "webapp-7.1.3"
        restart: "always"
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        links:
            - mysql
            - phpmyadmin
        volumes:
            - ${WEB_ROOT}:/var/www/html/src
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            - ./config/apache2/vhosts:/etc/apache2/sites-enabled
            - ./logs/apache2:/var/log/apache2
            - ~/.ssh/:/root/.ssh
            - ~/.gitconfig/:/root/.gitconfig
        environment:
          - DB_CONNECTION=mysql
          - DB_HOST=mysql
          - DB_PORT=${MYSQL_PORT}
          - DB_USERNAME=root
          - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    mysql:
        build: ./bin/mysql
        container_name: "5.7-mysql"
        restart: "always"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "sc-phpmyadmin"
        links:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=${MYSQL_PORT}
        ports:
            - "${PMA_WEB_PORT}:80"
        volumes:
            - /sessions
